Homework2
made-ml-in-prod-2021/truengineer pull request #3
Opened 2021-05-14 18:46 UTC by truEngineer

Все необходимые docker-команды представлены в `readme`, там же находится и проведенная самооценка (22 балла).

2021-05-22 17:11 UTC, Mikhail-M requested changes
верните код ml_project?

2021-05-22 17:13 UTC, Mikhail-M reviewed
За оптимизацию - 1.5 балла.
За валидацию -- 0.5 балла, оч скромно
За тесты 2, т.к используется продакшен модель, а не готовится в фикстуре, для модульных это был бы более подходящий вариант

Баллы: 17

Вернете код прошлой дз и поставлю аппрув

2021-05-22 17:53 UTC, truEngineer commented
ml_project вернул

2021-05-23 14:58 UTC, Mikhail-M approved these changes

2021-05-23 16:52 UTC, merged